# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.CharField(max_length=200)),
                ('revenue_text', models.IntegerField(default=0)),
                ('expenses_text', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='pub_date')),
                ('result', models.FloatField(default=0.0)),
            ],
        ),
    ]
