# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expenses_text',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='revenue_text',
            field=models.FloatField(default=0),
        ),
    ]
