# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170215_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='save_date',
            field=models.DateField(),
        ),
    ]
