# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170215_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='expenses',
            new_name='money',
        ),
        migrations.RemoveField(
            model_name='account',
            name='income',
        ),
        migrations.AddField(
            model_name='account',
            name='money_type',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
