# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170227_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='money_type',
            field=models.CharField(max_length=8),
        ),
    ]
